### ISSUE TITLE
Webpack 4

### ISSUE THREAD

**Issue by rickardliljeberg** [8427003/wildcards-entry-webpack-plugin#7]
Is there any support for webpack 4 comming?

This line failes for me: compilation.contextDependencies.push(globBasedir);

**Comment by ndelangen** [comment]
I have the same issue, here's my log:

```
(node:82035) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/wildcards-entry-webpack-plugin/index.js:63
            compilation.contextDependencies.push(globBasedir);
                                            ^

TypeError: compilation.contextDependencies.push is not a function
    at /Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/wildcards-entry-webpack-plugin/index.js:63:45
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/lib/Compiler.js:467:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/lib/Compilation.js:957:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/lib/Compilation.js:948:32)
    at _err0 (eval at create (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at /Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/dist/index.js:262:11
    at _class.runTasks (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:63:9)
    at UglifyJsPlugin.optimizeFn (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/dist/index.js:182:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/lib/Compilation.js:943:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/lib/Compilation.js:939:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/lib/Compilation.js:881:27)
    at hooks.make.callAsync.err (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/lib/Compiler.js:464:17)
    at _err0 (eval at create (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/lib/Compilation.js:749:12)
    at processModuleDependencies.err (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack/lib/Compilation.js:688:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
```

**Comment by ndelangen** [comment]
contextDependencies is now no longer an array, but a https://github.com/webpack/webpack/blob/master/lib/util/SortableSet.js#L16

I think converting `.push` to `.add` will do the trick, I'll try.

**Comment by ndelangen** [comment]
Confirmed, I made a PR:
https://github.com/8427003/wildcards-entry-webpack-plugin/pull/9

**Comment by ferdinando-ferreira** [comment]
Does this maintain backward compatibility? Here is a suggestion to keep this working without changes in the previous versions of Webpack while fixing for webpack 4

>            if (Array.isArray(compilation.contextDependencies)) {
>                compilation.contextDependencies.push(globBasedir);
>            }
>            else {
>                compilation.contextDependencies.add(globBasedir);
>            }

**Comment by ferdinando-ferreira** [comment]
Made a pull request with the above mentioned suggestion at #10
